### ISSUE TITLE
Expand distribution definition

### ISSUE THREAD

**Issue by SpheMakh** [caracal-pipeline/adestruction#1]
Something along these lines:

```yaml
cpus_per_task: 15

caracal:
  all:
    start-worker: flag
    end-worker: inspect
  runs:
    - index: 0
      options:
        flag-flag_spw-enable: true
        flag-flag_spw-chans: "0:0~200"
        flag-flag_antennas-enable: true
        flag-flag_antennas: m001
    - index: 1
      options:
        flag-flag_antennas-enable: true
        flag-flag_antennas: m002,m003
    - index: 2
      options:

    - index: 3
      options:
        flag-flagenable: true
        flag-flag_spw-enable: true
        flag-flag_spw-chans: "0:0~200,0:1500~2047"
        flag_spw-ensure_valid: true
        flag-flag_antennas-enable: true
        flag-flag_antennas-antennas: m019,m020,m022,m028
```

**Comment by sphemakh** [comment]
settling on this for now:

```yaml
resources:
  ram: 10 Gb
  ncpu: 25 


shared:
  start-worker: flag
  end-worker: inspect

runs:
  - index: 0
      options:
        flag-flag_spw-enable: true
        flag-flag_spw-chans: "0:0~200"
        flag-flag_antennas-enable: true
        flag-flag_antennas: m001
  - index: 1
      options:
        flag-flag_antennas-enable: true
        flag-flag_antennas: m002,m003
  - index: 2
      options:

  - index: 3
      options:
        flag-flagenable: true
        flag-flag_spw-enable: true
        flag-flag_spw-chans: "0:0~200,0:1500~2047"
        flag_spw-ensure_valid: true
        flag-flag_antennas-enable: true
        flag-flag_antennas-antennas: m019,m020,m022,m028
```
